name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_AWS_KEY_EPSON }}" > ~/.ssh/epson-web.pem
        chmod 600 ~/.ssh/epson-web.pem

    - name: Add server to known hosts
      run: |
        ssh-keyscan -H ec2-43-208-146-54.ap-southeast-7.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: Deploy to Server
      run: |
        ssh -i ~/.ssh/epson-web.pem ubuntu@ec2-43-208-146-54.ap-southeast-7.compute.amazonaws.com "cd ~/epson && npm run deploy"
